core_articulos:
    resource: "@AdminBundle/Controller/ArticulosController.php"
    type:     annotation

core_administradores:
    resource: "@AdminBundle/Controller/AdministradoresController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /core

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

logoutadmin:
    path: /admin/logout