core_productos:
    resource: "@AdminBundle/Controller/ProductosController.php"
    type:     annotation

core_maps_distribuidor_directorio:
    resource: "@AdminBundle/Controller/MapsDistribuidorDirectorioController.php"
    type:     annotation

core_maps_distribuidor:
    resource: "@AdminBundle/Controller/MapsDistribuidorController.php"
    type:     annotation

core_familia:
    resource: "@AdminBundle/Controller/FamiliaController.php"
    type:     annotation

core_consejos:
    resource: "@AdminBundle/Controller/ConsejosController.php"
    type:     annotation

core_categoria:
    resource: "@AdminBundle/Controller/CategoriaController.php"
    type:     annotation

core_banners:
    resource: "@AdminBundle/Controller/BannersController.php"
    type:     annotation

core_articulos:
    resource: "@AdminBundle/Controller/ArticulosController.php"
    type:     annotation

core_administradores:
    resource: "@AdminBundle/Controller/AdministradoresController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /core

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

logoutadmin:
    path: /admin/logout