<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2017-07-10 11:37:38.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * CoreBundle\Entity\Productos
 *
 * @ORM\Entity(repositoryClass="CoreBundle\Repository\searchRepository")
 * @ORM\Table(name="productos", indexes={@ORM\Index(name="fk_productos_familia1_idx", columns={"id_familia"})})
 */
class Productos
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $id_familia;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    protected $imagen;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $aplicacion;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $beneficios;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $especificaciones;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $presentaciones;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $caracteristicas;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $info;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $activo;

    /**
     * @Gedmo\Slug(separator="-", updatable=true, fields={"nombre"})
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $slug;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $metakeys;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $metadesc;

    /**
     * @Gedmo\Timestampable(on="create", field="creado")
     *
     * @ORM\Column(type="datetime")
     */
    protected $created_at;

    /**
     * @Gedmo\Timestampable(on="update", field="actualizado")
     *
     * @ORM\Column(type="datetime")
     */
    protected $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="Familia", inversedBy="productos")
     * @ORM\JoinColumn(name="id_familia", referencedColumnName="id", nullable=false)
     */
    protected $familia;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \CoreBundle\Entity\Productos
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of id_familia.
     *
     * @param integer $id_familia
     * @return \CoreBundle\Entity\Productos
     */
    public function setIdFamilia($id_familia)
    {
        $this->id_familia = $id_familia;

        return $this;
    }

    /**
     * Get the value of id_familia.
     *
     * @return integer
     */
    public function getIdFamilia()
    {
        return $this->id_familia;
    }

    /**
     * Set the value of nombre.
     *
     * @param string $nombre
     * @return \CoreBundle\Entity\Productos
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get the value of nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set the value of descripcion.
     *
     * @param string $descripcion
     * @return \CoreBundle\Entity\Productos
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get the value of descripcion.
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set the value of imagen.
     *
     * @param string $imagen
     * @return \CoreBundle\Entity\Productos
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * Get the value of imagen.
     *
     * @return string
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    /**
     * Set the value of aplicacion.
     *
     * @param string $aplicacion
     * @return \CoreBundle\Entity\Productos
     */
    public function setAplicacion($aplicacion)
    {
        $this->aplicacion = $aplicacion;

        return $this;
    }

    /**
     * Get the value of aplicacion.
     *
     * @return string
     */
    public function getAplicacion()
    {
        return $this->aplicacion;
    }

    /**
     * Set the value of beneficios.
     *
     * @param string $beneficios
     * @return \CoreBundle\Entity\Productos
     */
    public function setBeneficios($beneficios)
    {
        $this->beneficios = $beneficios;

        return $this;
    }

    /**
     * Get the value of beneficios.
     *
     * @return string
     */
    public function getBeneficios()
    {
        return $this->beneficios;
    }

    /**
     * Set the value of especificaciones.
     *
     * @param string $especificaciones
     * @return \CoreBundle\Entity\Productos
     */
    public function setEspecificaciones($especificaciones)
    {
        $this->especificaciones = $especificaciones;

        return $this;
    }

    /**
     * Get the value of especificaciones.
     *
     * @return string
     */
    public function getEspecificaciones()
    {
        return $this->especificaciones;
    }

    /**
     * Set the value of presentaciones.
     *
     * @param string $presentaciones
     * @return \CoreBundle\Entity\Productos
     */
    public function setPresentaciones($presentaciones)
    {
        $this->presentaciones = $presentaciones;

        return $this;
    }

    /**
     * Get the value of presentaciones.
     *
     * @return string
     */
    public function getPresentaciones()
    {
        return $this->presentaciones;
    }

    /**
     * Set the value of caracteristicas.
     *
     * @param string $caracteristicas
     * @return \CoreBundle\Entity\Productos
     */
    public function setCaracteristicas($caracteristicas)
    {
        $this->caracteristicas = $caracteristicas;

        return $this;
    }

    /**
     * Get the value of caracteristicas.
     *
     * @return string
     */
    public function getCaracteristicas()
    {
        return $this->caracteristicas;
    }

    /**
     * Set the value of info.
     *
     * @param string $info
     * @return \CoreBundle\Entity\Productos
     */
    public function setInfo($info)
    {
        $this->info = $info;

        return $this;
    }

    /**
     * Get the value of info.
     *
     * @return string
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Set the value of activo.
     *
     * @param boolean $activo
     * @return \CoreBundle\Entity\Productos
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get the value of activo.
     *
     * @return boolean
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Set the value of slug.
     *
     * @param string $slug
     * @return \CoreBundle\Entity\Productos
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get the value of slug.
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set the value of metakeys.
     *
     * @param string $metakeys
     * @return \CoreBundle\Entity\Productos
     */
    public function setMetakeys($metakeys)
    {
        $this->metakeys = $metakeys;

        return $this;
    }

    /**
     * Get the value of metakeys.
     *
     * @return string
     */
    public function getMetakeys()
    {
        return $this->metakeys;
    }

    /**
     * Set the value of metadesc.
     *
     * @param string $metadesc
     * @return \CoreBundle\Entity\Productos
     */
    public function setMetadesc($metadesc)
    {
        $this->metadesc = $metadesc;

        return $this;
    }

    /**
     * Get the value of metadesc.
     *
     * @return string
     */
    public function getMetadesc()
    {
        return $this->metadesc;
    }

    /**
     * Set the value of created_at.
     *
     * @param \DateTime $created_at
     * @return \CoreBundle\Entity\Productos
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param \DateTime $updated_at
     * @return \CoreBundle\Entity\Productos
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set Familia entity (many to one).
     *
     * @param \CoreBundle\Entity\Familia $familia
     * @return \CoreBundle\Entity\Productos
     */
    public function setFamilia(Familia $familia = null)
    {
        $this->familia = $familia;

        return $this;
    }

    /**
     * Get Familia entity (many to one).
     *
     * @return \CoreBundle\Entity\Familia
     */
    public function getFamilia()
    {
        return $this->familia;
    }

    public function __sleep()
    {
        return array('id', 'id_familia', 'nombre', 'descripcion', 'imagen', 'aplicacion', 'beneficios', 'especificaciones', 'presentaciones', 'caracteristicas', 'info', 'activo', 'slug', 'metakeys', 'metadesc', 'created_at', 'updated_at');
    }
}